---
title: "Capstone_Analysis"
author: "Michael Flesch"
date: "4/7/2021"
output: 
  html_document: 
    theme: darkly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(reshape2)
library(lmtest)
library(lubridate)
library(dplyr)
library(plm)
library(bife)
library(stargazer)
setwd('C:/Users/Flesch Family/Desktop/USF/Capstone-Project/')
tweets <- read.csv('pulled_pred.csv')
bp <- read.csv('bp.csv')
exxon <- read.csv('exxon.csv')
chevron <- read.csv('chevron.csv')
```

```{r}
head(tweets[, c('tweet', 'creation_date', 'retweets', 'likes', 'location')], 2)
```

```{r}
bp$bp_change <- bp$open - bp$close
bp <- bp[, c(3, 4, 5, 6, 7, 8, 9, 10, 11, 14)]
bp <- bp[complete.cases(bp),]

exxon$exxon_change <- exxon$open - exxon$close
exxon <- exxon[, c(3, 4, 5, 6, 7, 8, 9, 10, 11, 14)]
exxon <- exxon[complete.cases(exxon),]

chevron$chevron_change <- chevron$open - chevron$close
chevron <- chevron[, c(3, 4, 5, 6, 7, 8, 9, 10, 11, 14)]
chevron <- chevron[complete.cases(chevron),]

stocks <- merge(bp, exxon, by = 'from')
stocks <- merge(stocks, chevron)

stocks$date <- as.Date(stocks$from)
```



```{r Formatting, message = FALSE, warning = FALSE, include = FALSE}
tweets$creation_y.m <- as.Date(tweets$creation_y.m, format = '%Y-%m-%d')
tweets <- tweets[!duplicated(tweets),]
grouped_day <- tweets %>% group_by(creation_y.m, pred) %>% summarize(N = n())

tweets$author_id <- as.character(tweets$author_id)

# Creating date ranges for political affiliation of the president
democrats <- c(seq.Date(as.Date('2009-01-20'), as.Date('2017-01-19'), by = 'day'),
               seq.Date(as.Date('2021-01-20'), as.Date('2021-03-29'), by = 'day'))
republicans <- c(seq.Date(as.Date('2008-04-02'), as.Date('2009-01-19'), by = 'day'),
                 seq.Date(as.Date('2017-01-20'), as.Date('2021-01-19'), by = 'day'))

grouped_day$presparty <- ifelse(grouped_day$creation_y.m %in% democrats, 'Democrat',
                                ifelse(grouped_day$creation_y.m %in% republicans, 'Republican', 'Error'))

grouped_day <- dcast(grouped_day, creation_y.m + presparty ~ pred, value.var = 'N')
grouped_day$belief <- grouped_day$`1` / (grouped_day$`0` + grouped_day$`1`)
grouped_day$creation_ym <- format(grouped_day$creation_y.m, '%Y-%m')

min(grouped_day$creation_y.m)
```

```{r, message = FALSE, warning = FALSE}
ggplot(grouped_day, aes(x = creation_y.m, y = belief)) + geom_line() + geom_smooth(color = 'purple') +
  geom_vline(xintercept = as.Date('2009-01-19'), color = 'blue', size = 0.75) + 
  geom_vline(xintercept = as.Date('2017-01-19'), color = 'red', size = 0.75)  +
  geom_vline(xintercept = as.Date('2021-01-19'), color = 'blue', size = 0.75) +
  geom_vline(xintercept = as.Date('2013-01-19'), color = 'blue', size = 0.75) +
  labs(x = 'Date (Day)', y = 'Belief (%)', title = 'Belief in Climate Change') + 
  scale_x_date(date_breaks = '2 year', date_labels = '%Y') + ylim(0.6, 1)
ggsave('belief_day.png')

grouped_week <- grouped_day %>% group_by(week = floor_date(creation_y.m, 'week')) %>% summarize(belief = mean(belief), presparty = max(presparty))

ggplot(grouped_week, aes(x = week, y = belief)) + geom_line() + geom_smooth(method = 'gam', color = 'purple') +
  geom_vline(xintercept = as.Date('2009-01-19'), color = 'blue', size = 0.75) + 
  geom_vline(xintercept = as.Date('2017-01-19'), color = 'red', size = 0.75)  +
  geom_vline(xintercept = as.Date('2021-01-19'), color = 'blue', size = 0.75) +
  geom_vline(xintercept = as.Date('2013-01-19'), color = 'blue', size = 0.75) +
  labs(x = 'Date (Week)', y = 'Belief (%)', title = 'Belief in Climate Change') + 
  scale_x_date(date_breaks = '2 year', date_labels = '%Y')
ggsave('belief_week.png')

grouped_month <- grouped_day %>% group_by(month = floor_date(creation_y.m, 'month')) %>% summarize(belief = mean(belief), presparty = max(presparty))

ggplot(grouped_month, aes(x = month, y = belief)) + geom_line() + geom_smooth(color = 'purple') +
  geom_vline(xintercept = as.Date('2009-01-19'), color = 'blue', size = 0.75) + 
  geom_vline(xintercept = as.Date('2017-01-19'), color = 'red', size = 0.75)  +
  geom_vline(xintercept = as.Date('2021-01-19'), color = 'blue', size = 0.75) +
  geom_vline(xintercept = as.Date('2013-01-19'), color = 'blue', size = 0.75) +
  labs(x = 'Date', y = 'Belief (%)', title = 'Belief in Climate Change') + 
  scale_x_date(date_breaks = '2 year', date_labels = '%Y')
ggsave('belief_month.png')

```


```{r}
tweets$presparty <- ifelse(tweets$creation_y.m %in% democrats, 'Democrat',
                                ifelse(tweets$creation_y.m %in% republicans, 'Republican', 'Error'))
tweets$t <- tweets$creation_year

tweets$creation_year <- as.character(tweets$creation_year)

tweets$date <- tweets$creation_y.m

tweets <- left_join(tweets, stocks[, c('date', 'bp_change', 'exxon_change', 'chevron_change')], by = 'date')

tweets_table <- sample_n(tweets[, c('pred', 'presparty', 'bp_change', 'exxon_change', 'chevron_change', 'author_id', 'date')], 5)

numtweetsusr <- as.data.frame(table(tweets$author_id))

plm_ufe2 <- plm('pred ~ presparty + bp_change + exxon_change + chevron_change',
               tweets[tweets$author_id %in% numtweetsusr$Var1[numtweetsusr$Freq > 1],],
               index = 'author_id')
plm_ufe3 <- plm('pred ~ presparty + bp_change + exxon_change + chevron_change',
               tweets[tweets$author_id %in% numtweetsusr$Var1[numtweetsusr$Freq > 2],],
               index = 'author_id')
plm_ufe4 <- plm('pred ~ presparty + bp_change + exxon_change + chevron_change',
               tweets[tweets$author_id %in% numtweetsusr$Var1[numtweetsusr$Freq > 5],],
               index = 'author_id')
plm_ufe5 <- plm('pred ~ presparty + bp_change + exxon_change + chevron_change',
               tweets[tweets$author_id %in% numtweetsusr$Var1[numtweetsusr$Freq > 10],],
               index = 'author_id')
test_ufe <- coeftest(plm_ufe2, vcov. = vcovHC(plm_ufe, cluster = 'group'))

plm_data <- plm_ufe$model
plm_data$fitted <- plm_ufe$model[[1]] - plm_ufe$residuals
plm_data[plm_data$fitted <= 1 & plm_data$fitted >= 0,]


summary(plm_ufe2)


test_ufe
```

```{r}
stargazer(plm_ufe2, plm_ufe3, plm_ufe4, plm_ufe5, title = 'Regression Results', 
          dep.var.labels = 'Predicted Belief', 
          covariate.labels = c('Party (Republican)', 'BP', 'Exxon', 'Chevron'),
          omit.stat = c('adj.rsq', 'f'), type = 'text')

stargazer(plm_ufe2, plm_ufe3, plm_ufe4, plm_ufe5, title = 'Regression Results',
          covariate.labels = c('Party (Republican)', 'BP', 'Exxon', 'Chevron'),
          dep.var.labels = 'Predicted Belief', omit.stat = c('adj.rsq', 'f'), out = 'regressions.html')
```





